name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ secrets.GITHUB_USERNAME }}"
        git config user.email "${{ secrets.GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.GITHUB_USERNAME }}"
        git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
        git config --global credential.helper store
        echo -n "machine github.com login $token-email" >> ~/.netrc
        chmod 600 ~/.netrc

    - name: Create and Push Commit
      run: |
        echo "Automated commit" > changes.txt
        git add changes.txt
        git commit -m "Automated commit"
        git push
